### ISSUE TITLE
32 bit

### ISSUE THREAD

**Issue by Curtmcgirt** [mithrandyr/SimplySql#23] opened 2019-10-15 14:00 UTC
i need to call this with a program using 32-bit powershell, but it takes 15-30 seconds to import the module, vs only a couple of seconds on a normal 64-bit powershell. i can reproduce the delay in 32-bit ISE. with the -verbose switch, import-module shows the delay happens prior to any cmdlets/functions actually loading. 

VERBOSE: Loading module from path 'C:\Program Files (x86)\WindowsPowerShell\Modules\SimplySql\1.6.2\SimplySql.psm1'.

(the delay happens whether i have the module in program files or program files (x86)

the cmdlets all load pretty instantaneously once they start loading. any thoughts or tips?

**Comment by mithrandyr** [comment] 2019-10-15 19:07
@Curtmcgirt I'm not able to reproduce this issue.  Run 32bit powershell with the -noprofile switch and the import the SimplySql module and see how long it takes.

`c:\windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe -noprofile`

**Comment by Curtmcgirt** [comment] 2019-10-15 19:11
It took 30 seconds. I’ve also disabled my antivirus, as somebody suggested that might be real-time scanning.




@Curtmcgirt<https://github.com/Curtmcgirt> I'm not able to reproduce this issue. Run 32bit powershell with the -noprofile switch and the import the SimplySql module and see how long it takes.

c:\windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe -noprofile

—

**Comment by mithrandyr** [comment] 2019-10-15 20:06
So, once you start powershell (with the -noprofile switch), it loads quickly.. but doing the import takes a while? 
```
measure-command -expression {import-module SimplySql}
```

You could run, filter according to powershell.exe and see what is happening during the load -- that might indicate something.  Really not sure what else to tell you.  Can you reproduce this on another machine?  If you run a VM with a fresh install of windows 10, can you reproduce?

**Comment by mithrandyr** [comment] 2019-10-15 20:28
sorry.. the "you could run" was meant to say "you could run SysInternals ProcMon..."

**Comment by Curtmcgirt** [comment] 2019-10-15 20:31
I have reproduced on a couple of machines, windows 10 and server 2016, but they are in the same domain. On my personal windows 10 home machine, it imports very quickly on 32 bit.

I don't know of any group policies in the domain that would cause this, and I'm guessing it would be particularly strange to have a difference in behavior if I run 32 bit vs 64 bit. The software vendor suggested it might be CRL checking, but again I don't know why that would only affect 32 bit.

On Oct 15, 2019 3:06 PM, Mithrandyr <notifications@github.com> wrote:

So, once you start powershell (with the -noprofile switch), it loads quickly.. but doing the import takes a while?

measure-command -expression {import-module SimplySql}


You could run, filter according to powershell.exe and see what is happening during the load -- that might indicate something. Really not sure what else to tell you. Can you reproduce this on another machine? If you run a VM with a fresh install of windows 10, can you reproduce?

—

**Comment by Curtmcgirt** [comment] 2019-10-15 21:19
I tried procmon, but nothing jumped out at me as “this is what’s taking so long.” I admit this is probably environmental, but I can’t think of what would only affect 32-bit.




sorry.. the "you could run" was meant to say "you could run SysInternals ProcMon..."

**Comment by mithrandyr** [comment] 2020-02-29 15:44
Closing this as it appears environmental.

**Closed by mithrandyr** 2020-02-29 15:44 UTC
